openapi: 3.0.1
info:
  title: Vendor Statistics API
  description: API to get statistics for a vendor's products within a specific date range.
  version: 1.0.0
servers:
  - url: http://localhost:{port}
    description: Local server
    variables:
      port:
        default: 5000
paths:
  /statistics/{vendorId}:
    post:
      summary: Get statistics for a vendor's products
      description: Retrieve the number of products sold, total amount, hot sales, and unique customers for a vendor within a specified date range.
      tags:
        - Statistics
      parameters:
        - in: path
          name: vendorId
          required: true
          schema:
            type: string
          description: ID of the vendor for which to retrieve statistics.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:
                  type: string
                  format: date
                  description: The start date of the period for which to retrieve statistics.
                endDate:
                  type: string
                  format: date
                  description: The end date of the period for which to retrieve statistics.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successfully retrieved statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  numberOfProduct:
                    type: integer
                    description: Number of different products sold.
                  totalAmount:
                    type: number
                    description: Total amount of sales.
                  hotSales:
                    type: array
                    items:
                      type: object
                      properties:
                        productId:
                          type: string
                          description: The ID of the product.
                        quantity:
                          type: integer
                          description: Quantity of the product sold.
                        totalAmount:
                          type: number
                          description: Total amount from sales of the product.
                  uniqueCustomers:
                    type: integer
                    description: Number of unique customers.
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Order:
      type: object
      properties:
        orderId:
          type: string
        deliveryAddress:
          type: string
        userId:
          type: string
        paymentMethod:
          type: string
        status:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
        totalAmount:
          type: number
        expectedDeliveryDate:
          type: string
          format: date
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Product:
      type: object
      properties:
        productId:
          type: string
        vendorId:
          type: string
        price:
          type: number
