paths:
  /toWishlist:
    post:
      tags:
        - Wishlist
      summary: "Add a new item to wishlist"
      description: "Add a new item to the wishlist"
      security:
        - token: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                userId:
                  type: "string"
                  example: "268dd4a0-9e23-441f-b7ba-890cce959387"
                productId:
                  type: "string"
                  example: "8bb67532-7d91-4e17-8f1c-a91e5178792e"
                price:
                  type: "number"
                  example: 45
              required:
                - userId
                - productId
                - price
      responses:
        "200":
          description: "Item added to wishlist successfully"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "success"
                  data:
                    type: "object"
                    properties:
                      productId:
                        type: "string"
                        example: "8bb67532-7d91-4e17-8f1c-a91e5178792e"
                      price:
                        type: "number"
                        example: 45
        "400":
          description: "Invalid request body"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "Error"
                  message:
                    type: "string"
                    example: "Invalid request body"
        "500":
          description: "Internal server error"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "Error"
                  message:
                    type: "string"
                    example: "Internal server error"
