name: Code Crafters E-commerce CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Set up environment variables
      run: |
        echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
        echo "MODE=${{ secrets.MODE }}" >> $GITHUB_ENV
        echo "DATABASE_DEVELOPMENT_URL=${{ secrets.DATABASE_DEVELOPMENT_URL }}" >> $GITHUB_ENV
        echo "DATABASE_TEST_URL=${{ secrets.DATABASE_TEST_URL }}" >> $GITHUB_ENV
        echo "DATABASE_PRODUCTION_URL=${{ secrets.DATABASE_PRODUCTION_URL }}" >> $GITHUB_ENV
        echo "EMAIL=${{ secrets.EMAIL }}" >> $GITHUB_ENV
        echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> $GITHUB_ENV

    - name: install dependencies
      run: npm install
    
    - name: build
      run: npm run build --if-present
    
    - name: run tests
      run: npm run test
